---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-secrets-vol-as-propfiles
  labels:
    version: 1.0.0
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "spring-cloud-kubernetes-consumer-service, app-a, app-b"
data:
  userid2-settings.properties: |-
    #
    # userid2-settings.properties:
    #
    value=theUserIDConfigMappD55
  password2-settings.properties: |-
    #
    password2-settings.properties:
    #
    value=thePassWordConfigMappD55

