---
apiVersion: v1
kind: ConfigMap
metadata:
  name: the-config
  labels:
    version: 1.0.0
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "spring-cloud-kubernetes-consumer-service, app-a, app-b"
data:
  games.properties: |-
    #
    # game.properties:
    #
    enemies=aliens
    lives=88
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
  ui.properties: |-
    #
    # ui.properties
    #
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice

