---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-spring-secrets-nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.1.103
    path: "/mnt/nfsshare/k8svolumes/data/secrets"