---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-spring-secrets-nfs
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Mi